export const BRAND_CONFIG = {
  name: 'NorthStack Digitals',
  tagline: 'You have the idea. We build the technology.',
  description: 'NorthStack Digitals builds websites, mobile apps, bots, AI tools, Minecraft mods and custom software — designed, built and delivered around what you actually need.',
  domain: 'northstackdigitals.com',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  adminUrl: process.env.NEXT_PUBLIC_ADMIN_URL || 'http://localhost:3001',
  supportEmail: 'contact@northstackdigitals.com',
  social: {
    discord: 'https://discord.gg/northstack',
    github: 'https://github.com/northstackdigitals',
    x: 'https://x.com/northstacktech',
  },
} as const;

export const BUSINESS_RULES = {
  defaultUpfrontPercentage: 50,
  defaultIncludedRevisions: 2,
  quoteExpirationDays: 14,
  maxAttachmentSizeBytes: 50 * 1024 * 1024, // 50 MB
  maxDeliverableSizeBytes: 250 * 1024 * 1024, // 250 MB
  currency: 'INR',
  paisePerRupee: 100,
} as const;

export const TIMELINE_SLAS = {
  STANDARD: {
    label: 'Standard',
    estimatedDays: 7,
    description: 'Target delivery in approximately 7 days.',
  },
  EXPRESS: {
    label: 'Express',
    estimatedDays: 3,
    description: 'Priority sprint: Target delivery in 2–3 days.',
  },
  NEXT_DAY: {
    label: 'Next Day',
    estimatedDays: 1,
    description: 'Ultra-fast delivery: Target delivery in approximately 24 hours.',
  },
  FLEXIBLE: {
    label: 'Flexible',
    estimatedDays: 14,
    description: 'Relaxed timeline for open-ended or complex milestones.',
  },
} as const;

export const BUDGET_RANGES = [
  { value: 'under-25k', label: 'Under ₹25,000' },
  { value: '25k-50k', label: '₹25,000 – ₹50,000' },
  { value: '50k-100k', label: '₹50,000 – ₹1,00,000' },
  { value: '100k-250k', label: '₹1,00,000 – ₹2,50,000' },
  { value: 'above-250k', label: '₹2,50,000+' },
  { value: 'custom', label: 'Custom / To be discussed' },
] as const;

export const PROJECT_TYPES = [
  'Website',
  'Web App',
  'Mobile App',
  'Desktop App',
  'Discord Bot',
  'Telegram Bot',
  'AI / LLM System',
  'Automation / Workflow',
  'Backend / API',
  'Database Architecture',
  'Minecraft Mod (Fabric / Forge / NeoForge)',
  'Minecraft Plugin / Server Network',
  'Gaming / Custom Mechanics',
  'Infrastructure / DevOps',
  'Custom Software',
  'Other',
] as const;

export const DEFAULT_SERVICES = [
  {
    id: 'srv_saas',
    title: 'Custom SaaS & Web Application',
    slug: 'custom-saas-web-application',
    shortDescription: 'Full-stack Next.js web application with authenticated dashboards, database architecture, and payment checkouts.',
    fullDescription: 'We design and develop bespoke, production-ready web platforms using Next.js App Router, TypeScript, Tailwind CSS, and PostgreSQL. Includes end-to-end authentication, RBAC authorization, transactional billing, real-time sync, and responsive interfaces.',
    startingPricePaise: 4500000,
    estimatedDaysDefault: 14,
    features: ['Next.js App Router & TypeScript', 'PostgreSQL & Prisma ORM', 'Authentication & Role-Based Access', 'Payment Gateway Integration', 'Fully Responsive UI (Desktop/Mobile)', 'SEO & Core Web Vitals Optimized'],
    deliverableTypes: ['Full Source Code Repository', 'Live Production Deployment', 'Admin Control Panel', 'Technical Documentation'],
    isFeatured: true,
    isPublished: true,
    category: { name: 'Websites & Web Apps', slug: 'websites-web-apps' },
    faqs: [
      { question: 'What tech stack do you use?', answer: 'We build with Next.js, React, TypeScript, Tailwind CSS, PostgreSQL, and Redis for maximum performance and maintainability.' },
      { question: 'Do I get the source code?', answer: 'Yes, full source code ownership and Git repository access are transferred upon final payment completion.' }
    ]
  },
  {
    id: 'srv_biz_web',
    title: 'High-Converting Business & Portfolio Website',
    slug: 'business-portfolio-website',
    shortDescription: 'Ultra-fast, typography-driven marketing website designed to convert visitors into qualified leads.',
    fullDescription: 'Custom bespoke marketing website designed with modern typography, subtle motion animations, dynamic Open Graph cards, structured Schema.org SEO, and frictionless contact/quote request workflows.',
    startingPricePaise: 2000000,
    estimatedDaysDefault: 5,
    features: ['Modern Minimalist Design Tokens', 'Dynamic Open Graph Social Cards', 'Sub-second Core Web Vitals Performance', 'Interactive Quote & Contact Intake', 'Dynamic Sitemap & Schema.org JSON-LD'],
    deliverableTypes: ['Vercel/Node Production Deployment', 'Source Code Repository', 'Asset Package'],
    isFeatured: true,
    isPublished: true,
    category: { name: 'Websites & Web Apps', slug: 'websites-web-apps' },
    faqs: [
      { question: 'How long does a business website take?', answer: 'Standard delivery target is 5 to 7 days depending on the number of bespoke pages and custom copy.' }
    ]
  },
  {
    id: 'srv_bot',
    title: 'Custom Discord Bot System',
    slug: 'custom-discord-bot',
    shortDescription: 'Bespoke Discord.js v14 bot with slash commands, interactive buttons, modal forms, and database persistence.',
    fullDescription: 'Production-ready Discord bot architecture engineered with Discord.js, REST slash command deployment, interactive modal workflows, database moderation logging, ticket management, and third-party API sync.',
    startingPricePaise: 1500000,
    estimatedDaysDefault: 4,
    features: ['Discord.js v14+ Architecture', 'Slash Commands & Autocomplete', 'Interactive Modals & Action Rows', 'PostgreSQL / Redis Persistence', 'Dockerized 24/7 Hosting Setup'],
    deliverableTypes: ['Clean TypeScript Bot Codebase', 'Deployment Dockerfile / VPS Setup Guide', 'Command Documentation'],
    isFeatured: true,
    isPublished: true,
    category: { name: 'Bots & Automation', slug: 'bots-automation' },
    faqs: [
      { question: 'Can the bot be hosted 24/7?', answer: 'Yes, we provide ready-to-run Docker Compose setups or assist with deployment to your VPS or cloud host.' }
    ]
  },
  {
    id: 'srv_rag',
    title: 'Enterprise RAG Knowledge Base & AI Agent',
    slug: 'enterprise-rag-ai-agent',
    shortDescription: 'Domain-specific AI agent equipped with private document embeddings, semantic vector search, and structured tool execution.',
    fullDescription: 'Advanced LLM integration leveraging hybrid vector search (Dense + BM25), semantic chunking, prompt engineering, and structured Zod output validation for accurate, hallucination-resistant domain responses.',
    startingPricePaise: 5000000,
    estimatedDaysDefault: 10,
    features: ['Hybrid Vector Search (pgvector)', 'Document Parsing & Chunking Pipeline', 'Structured Tool Calling (Function Calling)', 'Context Window Token Optimization', 'Privacy-Preserving Architecture'],
    deliverableTypes: ['Full AI Engine Source Code', 'Ingestion CLI Script', 'Interactive Chat Interface'],
    isFeatured: true,
    isPublished: true,
    category: { name: 'AI & Intelligent Systems', slug: 'ai-systems' },
    faqs: [
      { question: 'Which AI models are supported?', answer: 'We support Gemini 1.5/2.0, OpenAI GPT-4o, Claude 3.5 Sonnet, and open-source models via Ollama/vLLM.' }
    ]
  },
  {
    id: 'srv_mc',
    title: 'Minecraft Plugins, Mods & Server Systems',
    slug: 'minecraft-paper-plugin',
    shortDescription: 'Custom Fabric & Forge mods, Paper/Purpur plugins, custom entities, blocks, and high-performance server network mechanics.',
    fullDescription: 'Bespoke Minecraft engineering across client and server environments. We develop modern Fabric, NeoForge, and Forge mods (Mixins, custom items/blocks, screen handlers, networking packets) as well as optimized Paper/Purpur plugins with asynchronous chunk loading, PDC NBT structures, and 50ms tick-budget guarantees.',
    startingPricePaise: 1200000,
    estimatedDaysDefault: 5,
    features: ['Fabric, Forge & NeoForge Mod Development', 'Paper, Spigot & Purpur Server Plugins', 'Custom Entities, Blocks, Items & Screen Handlers', 'Mixins & Packet Synchronization', 'Folia Multi-Threaded Support', 'High-Performance 20 TPS Optimization'],
    deliverableTypes: ['Compiled Mod / Plugin JAR files', 'Full Java/Kotlin Source Code', 'Loom/Gradle Build Files', 'Configuration & Asset Package'],
    isFeatured: true,
    isPublished: true,
    category: { name: 'Gaming & Minecraft', slug: 'gaming-minecraft' },
    faqs: [
      { question: 'Do you develop client-side and server-side Minecraft mods?', answer: 'Yes, we develop client mods, server-side Fabric/Forge mods, custom GUI screen handlers, and hybrid client-server packet synchronization systems.' },
      { question: 'Which Minecraft versions and mod loaders are supported?', answer: 'We support Fabric, NeoForge, Forge, Quilt, Paper, Purpur, Spigot, and Velocity across modern (1.20.x, 1.21+) and legacy versions (1.8.9, 1.12.2, 1.16.5).' }
    ]
  },
  {
    id: 'srv_backend',
    title: 'Production REST/tRPC Backend & Database',
    slug: 'backend-database-api',
    shortDescription: 'Hardened backend service with schema migrations, Redis caching, JWT session security, and OpenAPI 3.1 contracts.',
    fullDescription: 'Layered backend architecture with strict operational error handling, connection pooling, sliding-window rate limiting, and automated database indexes.',
    startingPricePaise: 3000000,
    estimatedDaysDefault: 7,
    features: ['Layered 3-Tier Architecture', 'Prisma / PostgreSQL Migrations', 'Redis Caching & Sliding Window Rate Limiting', 'OpenAPI 3.1 Contract Specs'],
    deliverableTypes: ['Backend Codebase', 'Database Migration Scripts', 'OpenAPI Documentation'],
    isFeatured: false,
    isPublished: true,
    category: { name: 'Backend & Infrastructure', slug: 'backend-infrastructure' },
    faqs: []
  },
  {
    id: 'srv_mobile',
    title: 'Cross-Platform React Native Mobile App',
    slug: 'cross-platform-mobile-app',
    shortDescription: 'Native-feel iOS and Android application with Expo Router, offline state caching, and push notifications.',
    fullDescription: 'Modern mobile app built with Expo Managed Workflow, TypeScript, dynamic deep linking, secure device storage, and EAS build pipelines.',
    startingPricePaise: 6000000,
    estimatedDaysDefault: 18,
    features: ['Expo Router File Navigation', 'iOS & Android Native Builds', 'Push Notifications Integration', 'Offline Data Synchronization'],
    deliverableTypes: ['Expo/React Native Source Code', 'EAS Build Config', 'App Store / Play Store Build Files'],
    isFeatured: false,
    isPublished: true,
    category: { name: 'Mobile Apps', slug: 'mobile-apps' },
    faqs: []
  },
  {
    id: 'srv_custom',
    title: 'Bespoke Custom Software Solution',
    slug: 'bespoke-custom-software',
    shortDescription: 'Tailored technology development for specialized operational workflows and complex domain requirements.',
    fullDescription: 'Full lifecycle software engineering for requirements that extend beyond standard categories. Includes custom architectural design, milestone delivery, and comprehensive documentation.',
    startingPricePaise: 5000000,
    estimatedDaysDefault: 14,
    features: ['Custom Architecture Design', 'Milestone-Driven Execution', 'Comprehensive Unit & E2E Testing', 'Complete Intellectual Property Transfer'],
    deliverableTypes: ['Complete Software Package', 'Technical Documentation', 'Deployment Playbook'],
    isFeatured: false,
    isPublished: true,
    category: { name: 'Custom Software', slug: 'custom-software' },
    faqs: []
  }
];

export const DEFAULT_PORTFOLIO = [
  {
    id: 'port_vortex_tiers',
    title: 'Vortex Tiers — Competitive Minecraft PvP Ranking & Tierlist Platform',
    slug: 'vortextiers-minecraft-pvp-rankings',
    clientName: 'Vortex Tiers Community',
    summary: 'Full-stack player tier scoring platform tracking HT1 to LT5 ratings across 8 competitive PvP gamemodes with Discord OAuth & Java IGN verification.',
    contentMdx: 'Engineered a high-performance leaderboard and tierlist system for the competitive Minecraft PvP community. Features instant player search, tier bracket sorting across Crystal, Netherite Pot, Pot, Sword, UHC, SMP, Axe, and Mace, and seamless Discord integration.',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://vortextiers.xyz/',
    tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Minecraft PvP', 'Leaderboards'],
    completedAt: new Date('2026-02-28'),
    isFeatured: true,
    isPublished: true,
  },
  {
    id: 'port_nexflow_pay',
    title: 'NexFlow Pay — Unified Merchant Payment Automation Workspace',
    slug: 'nexflow-pay-payment-automation',
    clientName: 'NexFlow Technologies',
    summary: 'API-first payment automation and merchant operations layer connecting payment links, orders, automations, and device actions directly to FastAPI backends.',
    contentMdx: 'Architected a modern payment operations control center for merchants. Built with strict server-authorized session security, real-time order state tracking, zero client-side calculation leaks, and typed API service boundaries.',
    coverImage: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://nexflowpay.vercel.app/',
    tags: ['Next.js App Router', 'FastAPI Integration', 'FinTech', 'RBAC Security', 'Tailwind CSS'],
    completedAt: new Date('2026-02-20'),
    isFeatured: true,
    isPublished: true,
  },
  {
    id: 'port_canvas_os',
    title: 'CanvasOS — Infinite Visual Architecture & Diagramming for Developers',
    slug: 'canvasos-infinite-developer-canvas',
    clientName: 'CanvasOS Dev Studio',
    summary: 'Local-first infinite, nestable canvas for software architects and engineering teams to diagram C4 models and system architectures with Git-inspired rollback history.',
    contentMdx: 'Developed an infinite canvas workspace where every node can open into another full nested canvas indefinitely. Features local-first IndexedDB storage, non-destructive named snapshots, and zero-telemetry offline execution.',
    coverImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://canvaos.vercel.app/',
    tags: ['Local-First', 'IndexedDB', 'Infinite Canvas', 'C4 Architecture', 'Developer Tools'],
    completedAt: new Date('2026-02-10'),
    isFeatured: true,
    isPublished: true,
  },
  {
    id: 'port_discord_bot_network',
    title: "Tanmay's Discord Bot Ecosystem & Multi-Guild Automation",
    slug: 'tanmays-discord-bot-ecosystem',
    clientName: 'Vortex Network & Gaming Communities (discord.gg/hzhvkzVVwM & discord.gg/dhvY2fbBSa)',
    summary: 'Production multi-guild Discord bot infrastructure with auto-moderation, custom tickets, economy, level progression, and Minecraft tier verification.',
    contentMdx: 'Engineered custom Discord automation bots serving active gaming communities. Verified by client praise (@nox: "like the bot according to ur liking? Yes thanks!"). Engineered with Discord.js/Python, modal interactive flows, transcript logging, and 99.99% uptime.',
    coverImage: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://tanmaygarg2009.github.io/Discord-Bot/',
    tags: ['Discord.js', 'Python', 'Slash Commands', 'Ticket System', 'Verified Proof'],
    completedAt: new Date('2026-01-25'),
    isFeatured: true,
    isPublished: true,
  },
  {
    id: 'port_vortex_api',
    title: 'Vortex Tiers High-Throughput REST API Engine',
    slug: 'vortextiers-rest-api-engine',
    clientName: 'Vortex Tiers & Modrinth Mod Community',
    summary: 'Hardened, cached RESTful API engine powering live in-game Fabric/Forge mods (Tier Tagger Mod on Modrinth) and external webhooks with sub-30ms response times.',
    contentMdx: 'Designed and deployed high-performance REST API endpoints consumed by client-side Minecraft mods on Modrinth. Implemented sliding-window rate limiting, Redis caching layers, and real-time player UUID tier lookups.',
    coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://api.vortextiers.xyz',
    tags: ['REST API', 'Redis Caching', 'Modrinth Integration', 'Rate Limiting', 'OpenAPI'],
    completedAt: new Date('2026-02-05'),
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 'port_vortex_verify',
    title: 'Vortex Tiers Microsoft Device & Discord Identity Verification Portal',
    slug: 'vortextiers-microsoft-discord-verification',
    clientName: 'Vortex Network',
    summary: 'Secure identity verification gateway linking authentic Minecraft Java Edition IGN UUIDs to Discord profiles using Microsoft Device Flow.',
    contentMdx: 'Built a tamper-proof verification portal preventing alt accounts and ban evasion. Leveraged Microsoft OAuth Device Flow and Discord Gateway to automatically synchronize verified server roles and competitive player standings.',
    coverImage: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://verify.vortextiers.xyz/',
    tags: ['Microsoft OAuth', 'Discord Verification', 'Identity Security', 'Minecraft Java', 'Next.js'],
    completedAt: new Date('2026-01-30'),
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 'port_vortex_apply',
    title: 'Vortex Tiers Staff Recruitment & Testing Platform',
    slug: 'vortextiers-staff-recruitment-portal',
    clientName: 'Vortex Staff Operations',
    summary: 'End-to-end recruitment management portal for Tier Testers, Moderators, and Event Staff with Discord OAuth and PvP clip submissions.',
    contentMdx: 'Multi-stage application pipeline featuring Discord authentication, structured PvP skill questionnaires, video evidence clip parsing, and staff evaluation review dashboards.',
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://apply.vortextiers.xyz/',
    tags: ['Application Portal', 'Queue Moderation', 'Video Review', 'Discord OAuth', 'Next.js'],
    completedAt: new Date('2026-01-18'),
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 'port_chem_mcp',
    title: 'Organic Chemistry AI MCP Server Testing & Admin Studio',
    slug: 'organic-chemistry-mcp-studio',
    clientName: 'BioChem AI Research',
    summary: 'Interactive testing interface and administrative dashboard for Model Context Protocol (MCP) server evaluating organic chemical reactions and molecular structures.',
    contentMdx: 'Engineered an AI tooling studio connecting LLMs to chemical synthesis tools via Model Context Protocol (MCP). Features structured schema inspection, live reaction testing, and automated chemical knowledge retrieval.',
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://chem-ten-dun.vercel.app/',
    tags: ['AI Tools', 'Model Context Protocol (MCP)', 'Chemistry Engine', 'Tailwind CSS', 'React'],
    completedAt: new Date('2026-01-12'),
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 'port_thelatracker',
    title: 'ThelaTrack — Real-Time Street Food Live Tracker PWA',
    slug: 'thelatrack-street-food-live-tracker',
    clientName: 'ThelaTrack Community',
    summary: '"Gali ka swaad, live" — Mobile-first Progressive Web App (PWA) with real-time vendor geolocation tracking and instant discovery.',
    contentMdx: 'Modern PWA connecting local street food enthusiasts with mobile street carts in real time. Features live geolocation tracking, vendor open/closed indicators, offline caching, and native mobile installability.',
    coverImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://thelatracker.vercel.app/',
    tags: ['Progressive Web App (PWA)', 'Geolocation', 'Real-Time Tracking', 'Next.js', 'Mobile-First'],
    completedAt: new Date('2025-12-28'),
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 'port_vortex_store',
    title: 'Vortex Network Official Minecraft Server Store & Community Portal',
    slug: 'vortex-network-minecraft-store',
    clientName: 'Vortex Network (play.vortextiers.xyz)',
    summary: 'Dark PvP aesthetic community portal and web store for server rank packages, battle pass perks, and live server player counters.',
    contentMdx: 'Custom branded web store built with Oxanium and JetBrains typography, Tebex/Razorpay checkout integration, one-click server IP copy (play.vortextiers.xyz), and real-time server status ping.',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
    galleryImages: [],
    liveUrl: 'https://store.vortextiers.xyz/',
    tags: ['Minecraft Store', 'Tebex / Payments', 'Dark PvP UI', 'Gaming Community', 'Tailwind CSS'],
    completedAt: new Date('2025-12-15'),
    isFeatured: false,
    isPublished: true,
  },
];

export const DEFAULT_REVIEWS = [
  {
    id: 'rev_1',
    rating: 5,
    headline: 'Like the bot according to ur liking? Yes, thanks!',
    comment: 'Custom multi-guild Discord bot engineered with moderation, tickets, economy, and real-time Minecraft tier verification. Delivered cleanly, fast, and exactly to our server specifications.',
    isPublished: true,
    isFeatured: true,
    user: { name: 'Nox (@nox)' },
    project: { title: 'Vortex Discord Bot & Server Infrastructure' },
    proofImage: '/proofs/discord-bot-review-proof.png',
    verifiedDiscordServer: 'discord.gg/hzhvkzVVwM',
  },
  {
    id: 'rev_2',
    rating: 5,
    headline: 'Payment operations in flow with zero browser logic leaks.',
    comment: 'NorthStack built our full merchant portal, payment link generator, and device sync layers directly connected to our FastAPI backend with incredible speed and rock-solid architecture.',
    isPublished: true,
    isFeatured: true,
    user: { name: 'NexFlow Merchant Operations' },
    project: { title: 'NexFlow Pay Workspace' },
  },
  {
    id: 'rev_3',
    rating: 5,
    headline: 'Infinite nestable canvas with local-first IndexedDB performance.',
    comment: 'The developer diagramming tool and nested canvas engine was architected with zero-telemetry, Git-inspired snapshots, and lightning fast performance.',
    isPublished: true,
    isFeatured: true,
    user: { name: 'CanvasOS Dev Studio' },
    project: { title: 'CanvasOS Architecture Engine' },
  },
  {
    id: 'rev_4',
    rating: 5,
    headline: 'Flawless Microsoft Device verification and PvP tierlists.',
    comment: 'Automated our player tier ranking across 8 gamemodes and eliminated alt accounts with the Microsoft device auth portal. 10/10 engineering.',
    isPublished: true,
    isFeatured: true,
    user: { name: 'Vortex Tiers Staff Lead' },
    project: { title: 'Vortex Tiers & Verify Portal' },
  },
];

export * from './runtime-credentials';


